### ISSUE TITLE
Choose a licence

### ISSUE THREAD

**Issue by hoheinzollern** [ndslusarz/LDL_coq#28]
As per title. Possible valid options are CeCILL-C (same as MathComp-analysis), LGPL, MIT.

See [best practices in the Coq manifesto](https://github.com/coq-community/manifesto?tab=readme-ov-file#best-practices)

**Comment by ndslusarz** [comment]
Good point, I didn't realise it wasn't added - any particular preference?

**Comment by ndslusarz** [comment]
License added
